server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod

management:
  health:
    circuitbreakers:
      enabled: true
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: always


resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        sliding-window-size: 10
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED

    retry:
      instances:
        ratingHotelBreaker:
          max-attemps: 3
          wait-duration: 5s

