server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
    driver: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8085
  profiles:
    active: prod
